-- CreateEnum
CREATE TYPE "AiRecommendationTopic" AS ENUM ('WORKFORCE_CERTIFICATES', 'WORKFORCE_TRAINING', 'WORKFORCE_LEAVE', 'LABOUR_RELATIONS', 'HAZARD_REPORTS', 'AUDIT_FINDINGS', 'LEGAL_COMPLIANCE', 'RISK_ASSESSMENTS', 'SAFETY_INSPECTIONS', 'MEDICAL_SURVEILLANCE', 'STATUTORY_APPOINTMENTS', 'IOD_CLAIMS', 'TAILINGS', 'CLOSURE_REHABILITATION', 'EXPLOSIVES', 'REGULATORY_NOTICES', 'PERMITS', 'PERMITS_TO_WORK', 'CONTRACTORS', 'SECURITY_INCIDENTS', 'CCTV', 'PATROLS', 'VISITORS', 'EXPENSES', 'PAYEES', 'INVOICES', 'PURCHASE_ORDERS', 'SUPPLIERS', 'PAYROLL', 'MAINTENANCE', 'EQUIPMENT', 'PRODUCTION', 'SENSORS', 'ENVIRONMENT', 'EMERGENCY_PREPAREDNESS', 'GROUND_CONTROL', 'VENTILATION', 'MINE_RESCUE', 'USER_ACCOUNTS', 'GENERAL');

-- AlterTable
ALTER TABLE "AiRecommendation" ADD COLUMN     "topic" "AiRecommendationTopic";

