interface MineLike {
  name: string;
  logoDataUri?: string | null;
}

function esc(value: string) {
  return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

const baseStyle = `
  * { box-sizing: border-box; }
  body { font-family: -apple-system, "Segoe UI", Arial, Helvetica, sans-serif; color: #1c2536; margin: 0; background: #f4f5f7; }
  .sheet { max-width: 780px; margin: 0 auto; background: #ffffff; }
  .accent { height: 8px; background: linear-gradient(90deg, #c48a1f, #d9a441); }
  .content { padding: 32px 36px 40px; }
  .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 24px; gap: 16px; }
  .brand { display: flex; align-items: center; gap: 12px; }
  .brand img { width: 46px; height: 46px; object-fit: contain; border-radius: 8px; border: 1px solid #eceff3; }
  .mine { font-size: 17px; font-weight: 700; }
  .gendate { font-size: 11px; color: #6b7280; margin-top: 2px; }
  .title { font-size: 20px; font-weight: 800; text-align: right; text-transform: uppercase; letter-spacing: 0.03em; color: #c48a1f; }
  table { width: 100%; border-collapse: collapse; font-size: 12.5px; margin-bottom: 22px; border: 1px solid #eceff3; border-radius: 10px; overflow: hidden; }
  th { text-align: left; font-size: 10px; text-transform: uppercase; letter-spacing: 0.04em; color: #6b7280; background: #f8f9fb; padding: 8px 10px; border-bottom: 1px solid #eceff3; }
  th.right { text-align: right; }
  h2.section { font-size: 12px; text-transform: uppercase; letter-spacing: 0.04em; color: #6b7280; margin: 20px 0 8px; }
  .footer { margin-top: 28px; text-align: center; font-size: 10.5px; color: #b0b6c0; }
  .note { font-size: 11px; color: #9ca3af; margin-bottom: 20px; }
`;

function header(mine: MineLike, title: string, generatedAt: Date) {
  return `<div class="header">
    <div class="brand">
      ${mine.logoDataUri ? `<img src="${mine.logoDataUri}" alt="${esc(mine.name)}" />` : ""}
      <div>
        <div class="mine">${esc(mine.name)}</div>
        <div class="gendate">Generated ${generatedAt.toLocaleString()}</div>
      </div>
    </div>
    <div class="title">${esc(title)}</div>
  </div>`;
}

interface BalanceSheetLike {
  asOf: string;
  assets: { cashAndEquivalents: number; accountsReceivable: number; inventory: number; total: number };
  liabilities: { accountsPayable: number; total: number };
  equity: { retainedEarnings: number; total: number };
}

export function renderBalanceSheetHtml(sheet: BalanceSheetLike, mine: MineLike, generatedAt: Date) {
  const money = (n: number) => n.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  const row = (label: string, value: number, bold = false) => `<tr>
    <td style="padding:${bold ? "8px" : "6px"} 12px;border-bottom:1px solid #eceff3;font-weight:${bold ? 700 : 400};">${esc(label)}</td>
    <td style="padding:${bold ? "8px" : "6px"} 12px;border-bottom:1px solid #eceff3;text-align:right;font-weight:${bold ? 700 : 600};">${money(value)}</td>
  </tr>`;

  return `<!doctype html>
<html><head><meta charset="utf-8" /><title>Balance Sheet</title><style>${baseStyle}</style></head>
<body><div class="sheet"><div class="accent"></div><div class="content">
  ${header(mine, "Balance Sheet", generatedAt)}
  <div class="note">Management accounts, estimated from recorded transactions as of ${new Date(sheet.asOf).toLocaleString()}. Not a substitute for formal audited financial statements.</div>

  <h2 class="section">Assets</h2>
  <table><tbody>
    ${row("Cash & Equivalents", sheet.assets.cashAndEquivalents)}
    ${row("Accounts Receivable", sheet.assets.accountsReceivable)}
    ${row("Inventory", sheet.assets.inventory)}
    ${row("Total Assets", sheet.assets.total, true)}
  </tbody></table>

  <h2 class="section">Liabilities</h2>
  <table><tbody>
    ${row("Accounts Payable", sheet.liabilities.accountsPayable)}
    ${row("Total Liabilities", sheet.liabilities.total, true)}
  </tbody></table>

  <h2 class="section">Equity</h2>
  <table><tbody>
    ${row("Retained Earnings", sheet.equity.retainedEarnings)}
    ${row("Total Equity", sheet.equity.total, true)}
  </tbody></table>

  <div class="footer">Generated by Mine Guard</div>
</div></div></body></html>`;
}

interface JournalEntryLike {
  date: Date;
  type: "INCOME" | "EXPENSE";
  description: string;
  amount: number;
  currency: string;
  runningBalance: number;
}

export function renderJournalHtml(entries: JournalEntryLike[], mine: MineLike, generatedAt: Date) {
  const money = (n: number, currency: string) => `${currency} ${n.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  const rows = entries
    .map(
      (e, i) => `<tr style="background:${i % 2 === 0 ? "#ffffff" : "#fafafa"};">
        <td style="padding:8px 10px;border-bottom:1px solid #eceff3;">${e.date.toLocaleDateString()}</td>
        <td style="padding:8px 10px;border-bottom:1px solid #eceff3;">${esc(e.description)}</td>
        <td style="padding:8px 10px;border-bottom:1px solid #eceff3;">${e.type === "INCOME" ? "Income" : "Expense"}</td>
        <td style="padding:8px 10px;border-bottom:1px solid #eceff3;text-align:right;font-weight:600;color:${e.type === "INCOME" ? "#16a34a" : "#e13b2e"};">
          ${e.type === "INCOME" ? "+" : "-"}${money(e.amount, e.currency)}
        </td>
        <td style="padding:8px 10px;border-bottom:1px solid #eceff3;text-align:right;">${money(e.runningBalance, e.currency)}</td>
      </tr>`
    )
    .join("");

  return `<!doctype html>
<html><head><meta charset="utf-8" /><title>Journal</title><style>${baseStyle}</style></head>
<body><div class="sheet"><div class="accent"></div><div class="content">
  ${header(mine, "Journal", generatedAt)}
  <table>
    <thead><tr><th>Date</th><th>Description</th><th>Type</th><th class="right">Amount</th><th class="right">Balance</th></tr></thead>
    <tbody>${rows || `<tr><td style="padding:10px;color:#9ca3af;" colspan="5">No journal entries in this period.</td></tr>`}</tbody>
  </table>
  <div class="footer">Generated by Mine Guard</div>
</div></div></body></html>`;
}
