-- AlterTable
ALTER TABLE "MineralListing" ADD COLUMN     "packaging" TEXT,
ADD COLUMN     "certifications" TEXT;

-- CreateTable
CREATE TABLE "MineralListingImage" (
    "id" TEXT NOT NULL,
    "listingId" TEXT NOT NULL,
    "fileName" TEXT NOT NULL,
    "fileMimeType" TEXT NOT NULL,
    "fileSize" INTEGER NOT NULL,
    "fileData" BYTEA NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "MineralListingImage_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "MineralListingImage" ADD CONSTRAINT "MineralListingImage_listingId_fkey" FOREIGN KEY ("listingId") REFERENCES "MineralListing"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- CreateEnum
CREATE TYPE "ContractCategory" AS ENUM ('TRUCKING_HAULAGE', 'GEOLOGICAL_SERVICES', 'DRILLING_BLASTING', 'EARTHMOVING_EXCAVATION', 'PLANT_EQUIPMENT_MAINTENANCE', 'ELECTRICAL_INSTRUMENTATION', 'CIVIL_CONSTRUCTION', 'ENVIRONMENTAL_REHABILITATION', 'SECURITY_SERVICES', 'CATERING_ACCOMMODATION', 'TRANSPORT_LOGISTICS', 'CONSULTING_PROFESSIONAL', 'SUPPLY_EQUIPMENT_MATERIALS', 'IT_TELECOMMUNICATIONS', 'OTHER');

-- AlterTable
ALTER TABLE "ContractOpportunity" ADD COLUMN     "category" "ContractCategory" NOT NULL DEFAULT 'OTHER';
